Fail on bad options to fake-image-create
fake-image-create currently just ignores options it doesn't know
about.  I'd rather see us being strict about this, so if we introduce
typos, etc, we find it.  Expand the getopt call for the extra args
passed in currently.

(if this gets too complicated, a quick re-write in python with
argparse would make things easier)

Change-Id: If1eb1774549463644fc1d667d17773c4e30cbb60

diff --git a/nodepool/tests/fake-image-create b/nodepool/tests/fake-image-create
--- a/nodepool/tests/fake-image-create
+++ b/nodepool/tests/fake-image-create
@@ -41,13 +41,23 @@ fi
 outfile=
 outtypes=("qcow2")
 
-TEMP=$(getopt -o o:t: -- "$@")
+TEMP=$(getopt -o xo:t: --long qemu-img-options:,no-tmpfs -- "$@")
+if [ $? -ne 0 ]; then
+    echo "Invalid option"
+    exit 1
+fi
 eval set -- "$TEMP"
 while true ; do
     case "$1" in
+        --no-tmpfs)
+            echo " -> set --no-tmpfs"; shift 1;;
+        --qemu-img-options)
+            echo " -> qemu-img-options: $2"; shift 2;;
         -o) outfile=$2; shift 2;;
         -t) IFS="," read -a outtypes <<< "$2"; shift 2;;
+        -x) echo " -> debugging enabled"; shift;;
         --) shift ; break ;;
+        *) echo "Unknown option : $1"; exit 1;;
     esac
 done
 
