Test that dib failures don't stop node builds
Test that when a dib image fails to build nodepool continues to build
nodes using images it does have available.

To test that dib actually fails check the logged subprocesses for the
tests for exit status of 127. This is the value that is returned when
the fake dib builds are explicitly told to fail.

Change-Id: Ie7c13af319141ec3cf8d43155358157e7d9274b8

diff --git a/nodepool/tests/fake-image-create b/nodepool/tests/fake-image-create
--- a/nodepool/tests/fake-image-create
+++ b/nodepool/tests/fake-image-create
@@ -7,6 +7,11 @@ echo "----"
 echo $*
 echo "----"
 
+if [[ "${SHOULD_FAIL}" == 'true' ]]; then
+    echo "Should fail is set, exiting with status 127"
+    exit 127
+fi
+
 if [[ "${DIB_RELEASE}" != "21" ]]; then
     echo "DIB_RELEASE not set correctly"
     exit 1
